#!/bin/bash

docker run --rm -it \
  -e AWS_REGION=$(aws configure get region) \
  -e AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id) \
  -e AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key) \
  coldog/autoscaling-rolling-update $@
